### ISSUE TITLE
Automatically clean out old files

### ISSUE THREAD

**Issue by matt1003** [her/central.vim#3]
I have some patches that will automatically clean out files older than x-days from these directories (where x can be configured to any number of days).

Would you be interested such functionality? I can put together a pull request.

**Comment by her** [comment]
Absolutely!! That’s such a cool idea. 

I know I occasionally will open up a file from a codebase I haven’t touched in a while and I’ll hit an old swap file. 

Sounds great @matt1003

**Comment by matt1003** [comment]
Cool. I will put together a pull request. It might take a couple of weeks, as I'm a bit busy at the moment.

**Comment by her** [comment]
https://github.com/her/central.vim/pull/4

Referencing the PR here.

**Comment by matt1003** [comment]
Enhancement now merged.
