### ISSUE TITLE
Branch Protection

### ISSUE THREAD

**Issue by her** [her/central.vim#6]
I know this can sometimes conjure up strong opinions so am curious what you think @matt1003 

I like having branch protection on master (so you can't push directly) and approval checks before merging PRs into master. 

So I think we could do two things:

* Turn on branch protection for master
* Enable a PR approval req before merging 

Overkill? Good idea? 

I think unless we both totally agree on each of these things, we shouldn't do it. Thoughts?

**Comment by matt1003** [comment]
Some would say it's a bit overkill for such a small repository, but I think its a good idea. It's worth getting in the habit of using good design practices. I would also like to see the vim linting automatically run on all pull requests.

**Comment by her** [comment]
Vim linting on all PRs would be good. I'll take a look at integrating that before turning any protections on. it's just us anyway :D

**Comment by her** [comment]
I'm going to close this issue as stale 🙂 After revisiting this I don't want to make process where it's not needed and things are fine as is for now.
