### ISSUE TITLE
$VIMHOME showing up wherever `vim` is invoked

### ISSUE THREAD

**Issue by her** [her/central.vim#7]
Wondering if this is a configuration on my part. Whenever I launch vim, I get a lovely `$VIMHOME` dir inside of whatever hierarchy I invoked `$ vim <file>` 

Any ideas @matt1003 ?

**Comment by matt1003** [comment]
That is less than ideal. I have never seen that before; however I have this a the top of my `~/.vimrc`:

```vim
if has('win32') || has ('win64')
  set shell=powershell
  set shellcmdflag=-command
  let $VIMHOME=$HOME.'/vimfiles'
else
  set shell=/bin/bash
  set shellcmdflag=-c
  let $VIMHOME=$HOME.'/.vim'
endif
```
Although it shouldn't be necessary to manually define `$VIMHOME` like that.

What is `$HOME` and `$VIMHOME` set to when this issue occurs?


```vim
:echo $HOME
:echo $VIMHOME
```

**Comment by matt1003** [comment]
Oh... I see what is happing. `$VIMHOME` is not defined by Vim itself, instead its something that I have defined in my personal `~/.vimrc`. That's a stupid mistake on my part; I will put together a fix asap!

**Comment by matt1003** [comment]
See pull request #8

**Comment by her** [comment]
This is merged. 👍
